<a href="https://colab.research.google.com/github/JaimeCabrera-Softtek/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

### Creating tensors


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.dim()

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.dim()

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.dim()

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [ ]:
TENSOR.dim()

5

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [ ]:
print(TENSOR[0][0])
print(TENSOR[0][0][0])
print(TENSOR[0][0][0][0][2])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor(3)


### Random tensors

In [ ]:
# Create a random tensor of size (10, 10, 10, 4)
random_tensor = torch.rand(10, 10, 10, 4)
random_tensor = torch.rand(size=(10, 10, 10, 4)) # Using size
random_tensor

tensor([[[[0.4913, 0.2710, 0.0386, 0.4154],
          [0.9125, 0.9654, 0.4789, 0.8086],
          [0.3023, 0.3212, 0.6996, 0.4668],
          ...,
          [0.1560, 0.2085, 0.1867, 0.7181],
          [0.2308, 0.4469, 0.3489, 0.6849],
          [0.3515, 0.2610, 0.4909, 0.5946]],

         [[0.8292, 0.1176, 0.7480, 0.5948],
          [0.5195, 0.5985, 0.0031, 0.2258],
          [0.3884, 0.4424, 0.7002, 0.9826],
          ...,
          [0.5597, 0.1936, 0.1831, 0.7997],
          [0.1323, 0.7390, 0.0594, 0.4635],
          [0.4645, 0.4572, 0.8437, 0.6306]],

         [[0.3701, 0.4790, 0.1434, 0.8458],
          [0.0842, 0.2032, 0.1096, 0.9714],
          [0.3978, 0.5077, 0.6879, 0.2876],
          ...,
          [0.1021, 0.4178, 0.3329, 0.5067],
          [0.8126, 0.3822, 0.6313, 0.5420],
          [0.8789, 0.6502, 0.0709, 0.1971]],

         ...,

         [[0.4698, 0.4277, 0.9224, 0.5414],
          [0.1899, 0.6376, 0.3103, 0.8870],
          [0.7916, 0.5078, 0.7423, 0.7169],
          

In [ ]:
random_tensor.dim()

4

In [ ]:
random_tensor.shape

torch.Size([10, 10, 10, 4])

In [ ]:
random_tensor[9][8]

tensor([[0.7606, 0.9493, 0.1880, 0.5408],
        [0.7687, 0.2221, 0.2804, 0.6644],
        [0.4458, 0.4697, 0.3456, 0.9099],
        [0.3395, 0.9846, 0.5811, 0.4459],
        [0.3730, 0.9458, 0.9778, 0.7619],
        [0.1293, 0.2590, 0.5936, 0.1662],
        [0.5330, 0.2056, 0.5622, 0.8063],
        [0.1469, 0.6196, 0.1905, 0.5822],
        [0.7111, 0.6950, 0.9218, 0.7299],
        [0.5856, 0.4417, 0.2477, 0.4692]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.dim()

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(10, 10))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(10, 10))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # what datatype is the tensor (e.g. float32 of float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [ ]:
# Change tensor datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4154, 0.6105, 0.1093, 0.5128],
        [0.6621, 0.1969, 0.3835, 0.6328],
        [0.6232, 0.4964, 0.8370, 0.3023]])

In [ ]:
# Find out some details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4154, 0.6105, 0.1093, 0.5128],
        [0.6621, 0.1969, 0.3835, 0.6328],
        [0.6232, 0.4964, 0.8370, 0.3023]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Divide by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Try out PyTorch in-built functions
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.div(tensor, 10))

tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([0.1000, 0.2000, 0.3000])


### Matrix multiplication

Two main ways of perfoming multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **iner dimensions** must match:

The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:

And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.
* `(2, 3) @ (3, 2)` -> `(2, 2)`






In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

### One of the most common errors in deep learning: shape erros

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [181]:
# The matrix multiplication operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [182]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [192]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [184]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [186]:
# Find the mean - note: the torch.mean() function requieres a tensor
# of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [187]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [197]:
# Find the position in tensor that has the minimum value with argmin() -> returns
# index position of target tensor where the minimum value occurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [196]:
# Find the position in tensor that has the minimum value with argmax()
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [219]:
# Let´s create a tensor
x = torch.arange(1., 21.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]),
 torch.Size([20]))

In [231]:
# Add an extra dimension
x_reshaped = x.reshape(1, 2, 5, 2)
x_reshaped, x_reshaped.shape

(tensor([[[[ 5.,  2.],
           [ 3.,  4.],
           [ 5.,  6.],
           [ 7.,  8.],
           [ 9., 10.]],
 
          [[11., 12.],
           [13., 14.],
           [15., 16.],
           [17., 18.],
           [19., 20.]]]]),
 torch.Size([1, 2, 5, 2]))

In [222]:
# Change the view
z = x.view(1, 20)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 torch.Size([1, 20]))

In [226]:
# Changing z changes x (because a view of a tensor shares the same
# memory as the original input)
z[:, 0] = 5 # z[:, 0] -> z[0][0]
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]))

In [230]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]])

In [234]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

print(f"\nNew tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")

Previous tensor: tensor([[[[ 5.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.],
          [ 9., 10.]],

         [[11., 12.],
          [13., 14.],
          [15., 16.],
          [17., 18.],
          [19., 20.]]]])
Previous shape: torch.Size([1, 2, 5, 2])

New tensor: tensor([[[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]],

        [[11., 12.],
         [13., 14.],
         [15., 16.],
         [17., 18.],
         [19., 20.]]])
New shape: torch.Size([2, 5, 2])


In [238]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_reshaped.squeeze()}")
print(f"Previous shape: {x_reshaped.squeeze().shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_reshaped.squeeze().unsqueeze(dim=3)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[[ 5.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]],

        [[11., 12.],
         [13., 14.],
         [15., 16.],
         [17., 18.],
         [19., 20.]]])
Previous shape: torch.Size([2, 5, 2])

New tensor: tensor([[[[ 5.],
          [ 2.]],

         [[ 3.],
          [ 4.]],

         [[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]],

         [[ 9.],
          [10.]]],


        [[[11.],
          [12.]],

         [[13.],
          [14.]],

         [[15.],
          [16.]],

         [[17.],
          [18.]],

         [[19.],
          [20.]]]])
New shape: torch.Size([2, 5, 2, 1])


In [239]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permutted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permutted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [242]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permutted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [244]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [245]:
# Let´s index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [246]:
# Let´s index in the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [265]:
# Let´s index in the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [249]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [266]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [275]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & Numpy

Numpy is a popular scientific numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [276]:
# Numpy array to tensor
import numpy as np

In [278]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy´s default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [279]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [282]:
# Tensor to Numpy array
tensor = torch.arange(1.0, 8.0)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

In [283]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 3., 4., 5., 6., 7., 8.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))